import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/user_profile.dart';
import '../models/worker_profile.dart';
import 'supabase_service.dart';
import 'user_profile_service.dart';

class AuthService {
  /// Currently authenticated Supabase user.
  static User? get currentUser {
    return SupabaseService.client?.auth.currentUser;
  }

  /// ID of the currently authenticated Supabase user.
  static String? get currentUserId {
    return currentUser?.id;
  }

  /// Stream of Supabase authentication state changes.
  static Stream<AuthState>? get authStateChanges {
    return SupabaseService.client?.auth.onAuthStateChange;
  }

  /// Fetches the UserProfile corresponding to the authenticated user.
  static Future<UserProfile?> fetchCurrentUserProfile() async {
    final uid = currentUserId;
    if (uid == null || uid.isEmpty) return null;
    return await UserProfileService.getProfile(uid);
  }

  /// Authenticates using email and password via Supabase Auth.
  static Future<AuthResponse?> signIn({
    required String email,
    required String password,
  }) async {
    if (!SupabaseService.isReady) {
      if (kDebugMode) {
        print('⚠️ [AuthService.signIn] Supabase is not configured.');
      }
      return null;
    }

    try {
      final response = await SupabaseService.client!.auth.signInWithPassword(
        email: email.trim(),
        password: password,
      );
      return response;
    } catch (e, stack) {
      if (kDebugMode) {
        print('⚠️ [AuthService.signIn] Error: $e\n$stack');
      }
      rethrow;
    }
  }

  /// Registers a new user via Supabase Auth and creates their user_profile.
  static Future<AuthResponse?> signUp({
    required String email,
    required String password,
    required String role, // 'customer', 'worker', 'cooperative_admin'
    String fullName = '',
    String phone = '',
    String address = '',
    String city = '',
    String state = '',
    String pincode = '',
    int experienceYears = 0,
    String? cooperativeId,
  }) async {
    if (!SupabaseService.isReady) {
      if (kDebugMode) {
        print('⚠️ [AuthService.signUp] Supabase is not configured.');
      }
      return null;
    }

    try {
      final response = await SupabaseService.client!.auth.signUp(
        email: email.trim(),
        password: password,
        data: {
          'full_name': fullName,
          'role': role,
        },
      );

      final user = response.user;
      if (user != null) {
        // Create user_profile record
        final profile = UserProfile(
          id: user.id,
          fullName: fullName,
          email: email.trim(),
          phone: phone,
          role: role,
          address: address,
          city: city,
          state: state,
          pincode: pincode,
          createdAt: DateTime.now(),
        );

        await UserProfileService.createProfile(profile);

        // If registered as worker, also create worker_profile record
        if (role == 'worker') {
          final workerProfile = WorkerProfile(
            id: '', // Generated by Supabase UUID
            userId: user.id,
            cooperativeId: cooperativeId,
            experienceYears: experienceYears,
            address: address,
            city: city,
            state: state,
            pincode: pincode,
            verificationStatus: 'pending',
            availabilityStatus: 'available',
            createdAt: DateTime.now(),
          );

          if (SupabaseService.isReady) {
            final data = workerProfile.toJson();
            data.remove('id');
            await SupabaseService.client!.from('worker_profile').insert(data);
          }
        }
      }

      return response;
    } catch (e, stack) {
      if (kDebugMode) {
        print('⚠️ [AuthService.signUp] Error: $e\n$stack');
      }
      rethrow;
    }
  }

  /// Signs out of the current Supabase Auth session.
  static Future<void> signOut() async {
    if (!SupabaseService.isReady) return;

    try {
      await SupabaseService.client!.auth.signOut();
    } catch (e, stack) {
      if (kDebugMode) {
        print('⚠️ [AuthService.signOut] Error: $e\n$stack');
      }
    }
  }
}
